# Generated by Django 5.0.6 on 2026-06-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('STATUS_UPDATE', 'Status Update'), ('CANCELLATION', 'Cancellation'), ('REMINDER', 'Reminder')], default='BOOKING', max_length=20),
        ),
    ]
